### ISSUE TITLE
Prototype roadmap

### ISSUE THREAD

**Issue by apasto** [apasto/decorrelate-grids#2]
# TO-DO list, from concept to prototype

## To be implemented

- [x] script: window half size in output filenames
- [x] global regression (i.e. non-windowed)
- [ ] output in a single netcdf file, with fields
- [ ] example data, synthesized or from a real case (e.g. real topography, generate random (smooth) c0, c1 and synthesize correlated observable, masking a real uncorrelated signal)
- [ ] unit tests
- [x] package
- [x] multiprocessing parallelism
- [ ] _why xarray?_ the core rolling regression works fine for any array of the same size - we only need to assert for that.
- [ ] perform the decorrelation, including a remove-compute-restore "average preserving" strategy (otherwise the decorellation carries an implicit HP-filter side effect)

## Document these aspects of the implementation:

- [ ] aspect ratio (arising from range-azimuth coordinates in InSAR applications)
- [ ] managing nans
- [ ] output quantities
- [ ] predicted part and residuals
- [ ] documentation of script behaviour
- [ ] module: decorellation without file i/o (pending splitting of script and module)
